eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    user:
      name: prajwal
      password: prajwal@123
