spring:
  application:
    name: Order-Service
  security:
    user:
      name: admin       # your custom username
      password: prajwal@123

  datasource:
    url: jdbc:mysql://localhost:3306/POC?createDatabaseIfNotExist=true
    username: root
    password: "Prajwal@123"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

inventory:
  service:
    url: http://localhost:8081/api/inventory

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
